### ISSUE TITLE
No license mentioned in Readme.md

### ISSUE THREAD

**Issue by tom-leys** [Ralith/masterserve#1]
I was browsing your repositories (thanks for Hecs!) and noticed this library. It could prove useful (need to evaluate it first and look for alternatives) but would need a suitable license like MIT to use it for my commercial game.

Could you please clarify if there is an open license in your Readme.md file?

Thanks very much for your open source work

-Tom

**Comment by Ralith** [comment]
Thanks for your interest! This project isn't in a useful state at the moment, as you might guess from the dust, and I don't intend to return to it in the near future. I'll address this issue when I get back to it. Feel free to use the code here under the terms of any of Apache 2/MIT/Zlib at your choice if you really want, but I think for now the only really interesting thing in the repo is the design discussion in the README.

**Comment by tom-leys** [comment]
Thanks Ralith!

I didn't notice the dust. Fair enough! There's always far more good ideas (like this project) than there is time!

**Comment by Ralith** [comment]
I've now banged this into reasonable shape and documented the licensing. Still no promises about maintenance, but it may at least be an interesting reference.
